version: '3'
services:
  myeureka:
    image: "eureka:0.1"
    ports:
      - "8761:8761"
    networks:
      - webnet
  edge:
    image: "edge:0.1"
    ports:
      - "8081:8081"
    networks:
      - webnet
  301micro:
    image: "301micro:0.1"
    ports:
        - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
