server:
  port: 8081
spring:
  application:
    name: edge-service
  main:
    allow-bean-definition-overriding: true


zuul:
  routes:
    301javamicro:
      path: /employees
      url: http://localhost:8080
    home:
      path: /
      url: http://localhost:8080
  sensitive-headers: Cookie,Set-Cookie


security:
  oauth2:
    client:
      access-token-uri: https://dev-475527.okta.com/oauth2/default/v1/token
      client-id: '0oafs6ruloU1q3amy4x6'
      client-secret: '7OgRNRZJLCOsaTAYx2Q0PJ8fZrPI_6kDg2uhuIly'
      scope: openid profile email
      user-authorization-uri: https://dev-475527.okta.com/oauth2/default/v1/authorize
    resource:
      user-info-uri: https://dev-475527.okta.com/oauth2/default/v1/userinfo

feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true