server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: de7daddf92f04ecd0250
            clientSecret: a2e4ce8b59524d9c2590ed224330d04a1b4a5f1e
  application:
    name: edge-service
  main:
    allow-bean-definition-overriding: true



zuul:
  routes:
    301javamicro: /employees/**

  sensitive-headers: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#security:
#  oauth2:
#    client:
#      access-token-uri: https://dev-912784.okta.com/oauth2/default/v1/token
#      client-id: '0oaibgrorRm5bxLZD4x6'
#      client-secret: 'sSjWC_KKTCP3kRBHJUdlWGMWA08MkvvjDWEU9S7T'
#      scope: openid profile email
#      user-authorization-uri: https://dev-912784.okta.com/oauth2/default/v1/authorize
#    resource:
#      user-info-uri: https://dev-912784.okta.com/oauth2/default/v1/userinfo



#security:
#  oauth2:
#    client:
#      clientId: Iv1.31d3980af5014e2a
#      clientSecret: 85c41b20778f181a84a6729cec8dcded74db7766
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      user-info-uri: https://api.github.com/user
#      prefer-token-info: false

feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true