server:
  port: 8081
spring:
  application:
    name: edge-service
  main:
    allow-bean-definition-overriding: true


zuul:

  routes:
    employees-service: /employees/**
    301javamicro:
      path: /employees/**
      url: http://localhost:8080/employees
    home:
      path: /
      url: http://localhost:8080
  sensitive-headers: Cookie,Set-Cookie


security:
  oauth2:
    client:
      access-token-uri: https://dev-912784.okta.com/oauth2/default/v1/token
      client-id: '0oaibgrorRm5bxLZD4x6'
      client-secret: 'sSjWC_KKTCP3kRBHJUdlWGMWA08MkvvjDWEU9S7T'
      scope: openid profile email
      user-authorization-uri: https://dev-912784.okta.com/oauth2/default/v1/authorize
    resource:
      user-info-uri: https://dev-912784.okta.com/oauth2/default/v1/userinfo

feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true